### ISSUE TITLE
jnats-0.5.1.pom: Impossible to load parent

### ISSUE THREAD

**Issue by laugimethods** [nats-io/java-nats-streaming#18]
Issue probably related to [Add empty relative path to force parent POM resolution](https://github.com/nats-io/jnats/commit/4a5280696371e9ddb365591a352ff6f9fb14223d):

`libraryDependencies += "io.nats"  % "java-nats-streaming" % "0.1.0-SNAPSHOT" changing()`
works fine locally (`sbt compile`), but not on Wercker [logimethods / nats-connector-gatling](https://app.wercker.com/logimethods/nats-connector-gatling/runs/build/57c0bdccf52ca30100a61870?step=57c0bdd06423700001596796)
```
[info] Resolving io.nats#java-nats-streaming;0.1.0-SNAPSHOT ...
[info] Resolving io.nats#java-nats-streaming;0.1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0 ...
[info] Resolving io.nats#nats-parent;1.0 ...
[info] Resolving org.sonatype.oss#oss-parent;9 ...
[warn] Unable to reparse io.nats#java-nats-streaming;0.1.0-SNAPSHOT from Sonatype OSS Snapshots, using Fri Aug 26 17:22:13 UTC 2016
[info] Resolving io.nats#nats-parent;1.0 ...
[warn] Unable to reparse io.nats#java-nats-streaming;0.1.0-SNAPSHOT from Sonatype OSS Release, using Fri Aug 26 17:22:13 UTC 2016
[warn] Sorting results from io.nats#java-nats-streaming;0.1.0-SNAPSHOT, using Fri Aug 26 17:22:13 UTC 2016 and null
[warn] Sorting results from io.nats#java-nats-streaming;0.1.0-SNAPSHOT, using Fri Aug 26 17:22:13 UTC 2016 and null
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://oss.sonatype.org/content/groups/public/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[warn] 	module not found: io.nats#jnats;0.5.1
[warn] ==== local: tried
[warn]   /root/.ivy2/local/io.nats/nats-parent/1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Release: tried
[warn]   https://oss.sonatype.org/content/groups/public/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[info] Resolving com.google.protobuf#protobuf-java;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-java;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-parent;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-parent;3.0.0 ...
[info] Resolving com.google#google;1 ...
[info] Resolving com.google#google;1 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.guava#guava-parent;19.0 ...
[info] Resolving com.google.guava#guava-parent;19.0 ...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving org.slf4j#slf4j-parent;1.7.5 ...
[info] Resolving org.slf4j#slf4j-parent;1.7.5 ...
[info] downloading https://oss.sonatype.org/content/groups/public/io/nats/java-nats-streaming/0.1.0-SNAPSHOT/java-nats-streaming-0.1.0-20160826.172212-19.jar ...
[info] 	[SUCCESSFUL ] io.nats#java-nats-streaming;0.1.0-SNAPSHOT!java-nats-streaming.jar(bundle) (82ms)
[info] downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar ...
[info] 	[SUCCESSFUL ] com.google.protobuf#protobuf-java;3.0.0!protobuf-java.jar(bundle) (49ms)
[info] downloading https://repo1.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar ...
[info] 	[SUCCESSFUL ] com.google.guava#guava;19.0!guava.jar(bundle) (79ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (9ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.nats#jnats;0.5.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.nats:jnats:0.5.1
[warn] 		  +- io.nats:java-nats-streaming:0.1.0-SNAPSHOT (/pipeline/source/build.sbt#L17-18)
[warn] 		  +- com.logimethods:nats-connector-gatling_2.11:0.2.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: io.nats#jnats;0.5.1: not found
```

Actually, `libraryDependencies += "io.nats"  % "jnats" % "0.5.1"`
works also fine locally (`sbt compile`), but not on Wercker [logimethods / nats-connector-gatling](https://app.wercker.com/logimethods/nats-connector-gatling/runs/build/57c0b998ac7d5901008b6f09?step=57c0b99c6307540001bcf95f)

```
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://oss.sonatype.org/content/groups/public/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[warn] 	module not found: io.nats#jnats;0.5.1
[warn] ==== local: tried
[warn]   /root/.ivy2/local/io.nats/nats-parent/1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Release: tried
[warn]   https://oss.sonatype.org/content/groups/public/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.nats#jnats;0.5.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving io.nats#java-nats-streaming;v0.1.0 ...
[info] Resolving io.nats#java-nats-streaming;v0.1.0 ...
[info] Resolving io.nats#nats-parent;1.0 ...
[info] Resolving io.nats#nats-parent;1.0 ...
[info] Resolving org.sonatype.oss#oss-parent;9 ...
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#jnats;0.5.1 ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[info] Resolving io.nats#nats-parent;1.0-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://oss.sonatype.org/content/groups/public/io/nats/jnats/0.5.1/jnats-0.5.1.pom: Impossible to load parent for file:/root/.ivy2/cache/io.nats/jnats/ivy-0.5.1.xml.original. Parent=io.nats#nats-parent;1.0-SNAPSHOT
[warn] 	module not found: io.nats#jnats;0.5.1
[warn] ==== local: tried
[warn]   /root/.ivy2/local/io.nats/nats-parent/1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS Release: tried
[warn]   https://oss.sonatype.org/content/groups/public/io/nats/nats-parent/1.0-SNAPSHOT/nats-parent-1.0-SNAPSHOT.pom
[info] Resolving com.google.protobuf#protobuf-java;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-java;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-parent;3.0.0 ...
[info] Resolving com.google.protobuf#protobuf-parent;3.0.0 ...
[info] Resolving com.google#google;1 ...
[info] Resolving com.google#google;1 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.guava#guava-parent;19.0 ...
[info] Resolving com.google.guava#guava-parent;19.0 ...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving org.slf4j#slf4j-parent;1.7.5 ...
[info] Resolving org.slf4j#slf4j-parent;1.7.5 ...
[info] downloading https://repo1.maven.org/maven2/io/nats/java-nats-streaming/v0.1.0/java-nats-streaming-v0.1.0.jar ...
[info] 	[SUCCESSFUL ] io.nats#java-nats-streaming;v0.1.0!java-nats-streaming.jar(bundle) (13ms)
[info] downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar ...
[info] 	[SUCCESSFUL ] com.google.protobuf#protobuf-java;3.0.0!protobuf-java.jar(bundle) (48ms)
[info] downloading https://repo1.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar ...
[info] 	[SUCCESSFUL ] com.google.guava#guava;19.0!guava.jar(bundle) (80ms)
[info] downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (9ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.nats#jnats;0.5.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.nats:jnats:0.5.1 (/pipeline/source/build.sbt#L17-18)
[warn] 		  +- io.nats:java-nats-streaming:v0.1.0 (/pipeline/source/build.sbt#L18-19)
[warn] 		  +- com.logimethods:nats-connector-gatling_2.11:0.2.0-SNAPSHOT
[warn] 		io.nats:jnats:0.5.1 (/pipeline/source/build.sbt#L17-18)
[warn] 		  +- io.nats:java-nats-streaming:v0.1.0 (/pipeline/source/build.sbt#L18-19)
[warn] 		  +- com.logimethods:nats-connector-gatling_2.11:0.2.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: io.nats#jnats;0.5.1: not found
unresolved dependency: io.nats#jnats;0.5.1: not found
```

**Comment by laugimethods** [comment]
JNATS 0.5.1 has a reference to nats-parent version "1.0-SNAPSHOT" (https://oss.sonatype.org/service/local/repositories/releases/archive/io/nats/jnats/0.5.1/jnats-0.5.1.jar/!/META-INF/maven/io.nats/jnats/pom.xml), which does not exists (**_anymore_**) on the central Maven Repository (https://oss.sonatype.org/#nexus-search;quick~io.nats).

**Comment by mcqueary** [comment]
Hi there. I have been doing some release maintenance work over the weekend and I noticed the same issue with SNAPSHOT dependencies. Ultimately the right fix is that we shouldn't depend on a SNAPSHOT of our own parent POM :) (my fault for being messy). 

If I released 0.5.2, with a stable/visible nats-parent dependency, would that be an acceptable fix?

**Comment by laugimethods** [comment]
A release of JNats version 0.5.2, referenced by a new version of java-nats-streaming would be great!

**Comment by mcqueary** [comment]
jnats-0.5.2 is released. I'll have the java-nats-streaming-0.1.2 released shortly.

**Comment by mcqueary** [comment]
`jnats-0.5.3` and `java-nats-streaming-0.1.2` both released and have resolved the issue.

**Comment by laugimethods** [comment]
Issues indeed solved! Thank you!

BTW, I still have another issue I have to investigate (probably due to incompatible or missing librairies) :
```
16/08/30 12:12:00 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Thread-13,5,main]
java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$Descriptor.getOneofs()Ljava/util/List;
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.<init>(GeneratedMessageV3.java:1721)
	at io.nats.stan.protobuf.Protocol.<clinit>(Protocol.java:125)
	at io.nats.stan.protobuf.ConnectRequest.internalGetFieldAccessorTable(ConnectRequest.java:81)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(GeneratedMessageV3.java:123)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(GeneratedMessageV3.java:199)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:272)
	at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:248)
	at com.google.protobuf.TextFormat.print(TextFormat.java:71)
	at com.google.protobuf.TextFormat.printToString(TextFormat.java:118)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:106)
	at io.nats.stan.ConnectionImpl.connect(ConnectionImpl.java:139)
	at io.nats.stan.ConnectionFactory.createConnection(ConnectionFactory.java:40)
	at com.logimethods.connector.nats.to_spark.NatsStreamingToSparkConnectorImpl.receive(NatsStreamingToSparkConnectorImpl.java:223)
	at com.logimethods.connector.nats.to_spark.NatsToSparkConnector$1.run(NatsToSparkConnector.java:106)
```
